#define COMMAND_ID_AABB_FILLED 0.0
#define COMMAND_ID_AABB_EDGE 1.0
#define COMMAND_ID_AABB_TEXTURED 2.0
#define COMMAND_ID_CIRCLE_FILL 3.0
#define COMMAND_ID_CIRCLE_EDGE 4.0
#define COMMAND_ID_CHARACTER 5.0